[package]
name = "pdf2img-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "C-FFI bindings for pdf2img, used by Go and other languages"

[lib]
name = "pdf2img"
crate-type = ["cdylib", "staticlib"]

[dependencies]
pdf2img-core = { path = "../pdf2img-core" }
tokio = { workspace = true }
once_cell = { workspace = true }
tracing = { workspace = true }

[build-dependencies]
cbindgen = "0.26"
