/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** 单页渲染结果 */
export interface PageResult {
  /** 页码（从 1 开始） */
  pageNum: number
  /** 图像宽度 */
  width: number
  /** 图像高度 */
  height: number
  /** WebP 编码后的图像数据 */
  buffer: Buffer
  /** 是否成功 */
  success: boolean
  /** 错误信息（如果失败） */
  error?: string
  /** 渲染耗时（毫秒） */
  renderTime: number
  /** 编码耗时（毫秒） */
  encodeTime: number
}
/** 批量渲染结果 */
export interface RenderResult {
  /** 是否成功 */
  success: boolean
  /** 错误信息（如果整体失败） */
  error?: string
  /** PDF 总页数 */
  numPages: number
  /** 每页的渲染结果 */
  pages: Array<PageResult>
  /** 总耗时（毫秒） */
  totalTime: number
}
/** 渲染配置选项 */
export interface RenderOptions {
  /** 目标渲染宽度（默认 1280） */
  targetWidth?: number
  /** 扫描件/图片页面的降级宽度（默认 1024） */
  imageHeavyWidth?: number
  /** 最大缩放比例（默认 4.0） */
  maxScale?: number
  /** WebP 质量（1-100，默认 70） */
  webpQuality?: number
  /** 是否启用扫描件检测（默认 true） */
  detectScan?: boolean
}
/**
 * 从 PDF Buffer 渲染指定页面为 WebP
 *
 * # Arguments
 * * `pdf_buffer` - PDF 文件的二进制数据
 * * `page_nums` - 要渲染的页码数组（从 1 开始）
 * * `options` - 渲染配置选项
 *
 * # Returns
 * 包含所有页面渲染结果的对象
 */
export declare function renderPages(pdfBuffer: Buffer, pageNums: Array<number>, options?: RenderOptions | undefined | null): RenderResult
/**
 * 获取 PDF 页数（不渲染）
 *
 * # Arguments
 * * `pdf_buffer` - PDF 文件的二进制数据
 *
 * # Returns
 * PDF 的总页数
 */
export declare function getPageCount(pdfBuffer: Buffer): number
/** 检查 PDFium 库是否可用 */
export declare function isPdfiumAvailable(): boolean
/**
 * 预热 PDFium 库
 *
 * 在服务启动时调用，提前加载 PDFium 动态库并初始化，
 * 避免首次请求时的冷启动延迟（约 1-2 秒）
 *
 * # Returns
 * 预热耗时（毫秒）
 */
export declare function warmup(): number
/** 获取版本信息 */
export declare function getVersion(): string
